########################### VARIÁVEIS GLOBAIS ####################
spring.main.allow-bean-definition-overriding=true
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url = jdbc:mysql://localhost:3306/gso_esign_database?useTimezone=true&serverTimezone=UTC&useSSL=false
spring.jpa.show-sql=true
spring.session.jdbc.initialize-schema: always
spring.jpa.database-platform = org.hibernate.dialect.MySQL5Dialect
spring.jpa.generate-ddl=true
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.MySQL5InnoDBDialect
spring.jpa.properties.hibernate.jdbc.time_zone=UTC
# Hibernate ddl auto (create, create-drop, validate, update)
spring.jpa.hibernate.ddl-auto = update
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
spring.servlet.multipart.enabled=true
spring.servlet.multipart.file-size-threshold=2KB
server.port=9090
server.error.whitelabel.enabled=true
server.error.path=/error
config.token_key =715bc473-3b8c-4421-8a93-167b2efae24d
config.token_expiration =600000
#config.token_expiration =300000
config.header =Authorization
config.prefixo =Bearer
configs.esign.userginga=okmAdmin 
configs.esign.passginga=Prod!@2023!?
configs.esign.bpmusername=hossana.mosse
configs.esign.bpmpassword=@analista
configs.esign.password=$2a$05$dvQAXdOgI1cO0lDY6h9I3.iJGreEGL94qizgnGpR7BmfRZkKtSN/m

#configs.esign.password=$05$dvQAXdOgI1cO0lDY6h9I3.iJGreEGL94qizgnGpR7BmfRZkKtSN/m
configs.esign.apibaseurl=https://api.eu1.adobesign.com/api/rest/v6
configs.esign.refreshtokenurl=https://secure.eu1.adobesign.com/oauth/v2/refresh
########################### VARIÁVEIS GLOBAIS ####################

########################### CONFIGURACOES NA MAQUINA LOCAL ####################
spring.datasource.username = root
spring.datasource.password = root
configs.esign.uploads=uploads/
configs.esign.url=https://4679-154-118-205-139.ngrok-free.app/api/v1/receiver
configs.esign.server=  https://8d62-154-118-205-139.ngrok-free.app/api/v1/update/agreement/status

##########################  FIM  DAS CONFIGURACOES LOCAIS ########################




######################### CONFIGFURACOES NO SERVIDOR PARA GRUPO SIMPLES #################################

## TUDO PARA SOLENTE TESTE 
#spring.datasource.username = root
#spring.datasource.password = root
#configs.esign.uploads=/opt/uploads_esign_test/  PARA SOLENTE TESTE
#configs.esign.url=http://92.204.138.167:8585/gso_esign/api/v1/receiver
#configs.esign.server= https://services.gingabpm.com/gingabpm/api/v1/update/agreement/status



## TUDO PARA SOLENTE PRODUCAO   
#spring.datasource.username = root
#spring.datasource.password = root
#configs.esign.uploads=/opt/uploads_esign/   PARA SOLENTE PRODUCAO
#configs.esign.url=https://services.gingabpm.com/solente_esign/api/v1/receiver
#configs.esign.server= https://services.gingabpm.com/gingabpm/api/v1/update/agreement/status


############################  FIM  DAS CONFIGURACOES DO SERVIDOR ###########################

